version: '3.3' #Set Docker-compose version

services: #List of services / containers
  mariadb: #Define container's name in that file
    container_name: mariadb #Set container's name in docker
    image: mariadb:latest #Set image used (latest mariaDB image)
    volumes: #Set name and path for persisting datas
      -  mariadb_data:/var/lib/mysql
    restart: always #Set container's behavior when crashed (automatically restart)
    environment: #List of environment variable in that container
      MYSQL_ROOT_PASSWORD: tpgrp1 #Set root password
      MYSQL_DATABASE: tp_docker #Set database's name
      MYSQL_USER: user #Set an user
      MYSQL_PASSWORD: tpgrp1 #Set the password of MYSQL_USER

  wordpress: #Define container's name in that file
    container_name: wordpress #Set container's name in docker
    depends_on: #Container's names which that one depends
      - mariadb
    image: wordpress:latest #Set image used (latest wordpress image)
    volumes: #Set name and path for persisting datas
      - wordpress_data:/var/www/html
    ports: #Map ports between host machine and container
      - "8000:80"
    restart: always #Set container's behavior when crashed (automatically restart)
    environment: #List of environment variable in that container
      WORDPRESS_DB_HOST: mariadb:3306 #Set database container name and port 
      WORDPRESS_DB_USER: user #Set user
      WORDPRESS_DB_PASSWORD: tpgrp1 #Set password
      WORDPRESS_DB_NAME: tp_docker #Set database's name

  phpmyadmin: #Define container's name in that file
    container_name: phpmyadmin #Set container's name in docker
    depends_on: #Container's names which that one depends
      - mariadb
    image: phpmyadmin:latest #Set image used (latest phpmyadmin image)
    volumes: #Set name and path for persisting datas
      - phpmyadmin_data:/var/www/html
    ports: #Map ports between host machine and container
      - "8080:80"
    restart: always #Set container's behavior when crashed (automatically restart)
    environment: #List of environment variable in that container
      PHPMYADMIN_ROOT_PASSWORD: tpgrp1 #Set root password
      PHPMYADMIN_USER: user #Set user
      PHPMYADMIN_DATABASE: tp_docker #Set database's name
      PMA_HOST: mariadb #define host name of the MySQL server

volumes: #Initialize containers's volumes
  mariadb_data: {}
  wordpress_data: {}
  phpmyadmin_data: {}